// Generated by BUCKLESCRIPT VERSION 4.0.7, PLEASE EDIT WITH CARE
'use strict';


var Page = 0;

var Index = 0;

var P1 = 0;

var P2 = 0;

var P3 = 0;

exports.Page = Page;
exports.Index = Index;
exports.P1 = P1;
exports.P2 = P2;
exports.P3 = P3;
/* No side effect */
